# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
url:              'https://wonono1128.github.io'
baseurl:          'https://wonono1128.github.io'

author:
  name:           'Mark Otto'
  url:            'https://wonono1128.github.io'

paginate:         5

# Custom vars
version:          2.1.0


