# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      
url:              ''
baseurl:          '/'

author:
  name:           'Mark Otto'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
